version: '3'
services:
  spillman-etl:
    build:
      context: .
      dockerfile: Dockerfile
    image: sccity/spillman-etl:prod
    container_name: spillman-etl
    environment:
      - TZ=America/Denver
    privileged: true
    restart: unless-stopped